import { Product } from '@/components/providers/cart-provider';

export const products: Product[] = [
  {
    id: '1',
    name: 'T-Shirt Performance Pro',
    price: 45,
    originalPrice: 60,
    image: 'https://images.pexels.com/photos/6551415/pexels-photo-6551415.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'T-Shirts',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Noir', 'Blanc', 'Gris', 'Bleu'],
    description: 'T-shirt technique haute performance',
    detailedDescription: 'Notre T-shirt Performance Pro est conçu avec des matériaux techniques de dernière génération. Tissu respirant et évacuation optimale de l\'humidité pour vos entraînements les plus intenses. Coupe ajustée et confortable.',
    isNew: true,
    onSale: true,
  },
  {
    id: '2',
    name: 'Legging Ultra Flex',
    price: 65,
    image: 'https://images.pexels.com/photos/6551307/pexels-photo-6551307.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Leggings',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Noir', 'Violet', 'Gris foncé'],
    description: 'Legging ultra-stretch pour un confort maximal',
    detailedDescription: 'Le Legging Ultra Flex offre une liberté de mouvement incomparable grâce à son tissu 4-way stretch. Taille haute avec support compressif, poches latérales et finitions sans coutures pour éviter les irritations.',
    isNew: false,
    onSale: false,
  },
  {
    id: '3',
    name: 'Veste Training Elite',
    price: 85,
    image: 'https://images.pexels.com/photos/6551224/pexels-photo-6551224.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Vestes',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Noir', 'Gris', 'Bleu marine'],
    description: 'Veste technique pour l\'entraînement',
    detailedDescription: 'Veste polyvalente avec zip intégral, poches zippées et capuche ajustable. Matière déperlante et coupe-vent, parfaite pour l\'extérieur. Design moderne avec détails réfléchissants.',
    isNew: true,
    onSale: false,
  },
  {
    id: '4',
    name: 'Short Running Pro',
    price: 35,
    originalPrice: 45,
    image: 'https://images.pexels.com/photos/6551342/pexels-photo-6551342.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Shorts',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Noir', 'Bleu', 'Gris'],
    description: 'Short de course technique et léger',
    detailedDescription: 'Short de running avec caleçon intégré, poches latérales et cordon de serrage. Matière ultra-légère et séchage rapide. Bandes réfléchissantes pour la visibilité nocturne.',
    isNew: false,
    onSale: true,
  },
  {
    id: '5',
    name: 'Brassière Sport Intense',
    price: 40,
    image: 'https://images.pexels.com/photos/6551376/pexels-photo-6551376.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Brassières',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Noir', 'Blanc', 'Violet', 'Rose'],
    description: 'Brassière de sport haute performance',
    detailedDescription: 'Brassière avec support renforcé pour les activités haute intensité. Matière compressive et respirante, dos nageur pour une liberté de mouvement optimale. Bonnets amovibles.',
    isNew: true,
    onSale: false,
  },
  {
    id: '6',
    name: 'Sweatshirt Urban Style',
    price: 55,
    image: 'https://images.pexels.com/photos/6551294/pexels-photo-6551294.jpeg?auto=compress&cs=tinysrgb&w=600',
    category: 'Sweatshirts',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Gris', 'Noir', 'Beige'],
    description: 'Sweatshirt streetwear premium',
    detailedDescription: 'Sweatshirt à capuche avec coupe moderne oversize. Matière coton bio mélangé, poche kangourou et finitions de qualité premium. Perfect pour le sport et la ville.',
    isNew: false,
    onSale: false,
  },
];

export const categories = [
  'T-Shirts',
  'Leggings',
  'Vestes',
  'Shorts',
  'Brassières',
  'Sweatshirts',
];

export const sizes = ['XS', 'S', 'M', 'L', 'XL', 'XXL'];

export const colors = [
  'Noir',
  'Blanc',
  'Gris',
  'Gris foncé',
  'Bleu',
  'Bleu marine',
  'Violet',
  'Rose',
  'Beige',
];